modify ns changes for tvk installation

diff --git a/tvk-oneclick/tvk-oneclick b/tvk-oneclick/tvk-oneclick
--- a/tvk-oneclick/tvk-oneclick
+++ b/tvk-oneclick/tvk-oneclick
@@ -30,11 +30,11 @@ preflight_checks()
     read -r -p "Provide storageclass to be used for TVK/Application Installation(storageclass with default annotation will be take as default): " storage_class
   fi
   if [[ -z "$storage_class" ]];then
-	  storage_class=$(kubectl get storageclass | grep -w '(default)' | awk  '{print $1}')
-	  if [[ -z "$storage_class" ]];then
-	    echo "No default storage class found, need one to proceed";
-	    return 1
-          fi
+    storage_class=$(kubectl get storageclass | grep -w '(default)' | awk  '{print $1}')
+    if [[ -z "$storage_class" ]];then
+      echo "No default storage class found, need one to proceed";
+      return 1
+    fi
   fi
   check=$(kubectl tvk-preflight --storageclass "$storage_class" | tee /dev/tty)
   ret_code=$?
@@ -128,6 +128,7 @@ install_tvk()
   if  [[ -z ${input_config} ]];then
     read -r -p "Please provide the operator version to be installed (default - 2.1.0): " operator_version
     read -r -p "Please provide the triliovault manager version (default - v2.1.1-alpha): " triliovault_manager_version
+    read -r -p "Namespace name in which TVK should be installed: (default - default): " tvk_ns 
     read -r -p "Proceed even if resource exists y/n (default - y): " if_resource_exists_still_proceed
   fi
   if [[ -z "$if_resource_exists_still_proceed" ]];then
@@ -139,11 +140,23 @@ install_tvk()
   if [[ -z "$triliovault_manager_version" ]];then
     triliovault_manager_version='v2.1.1-alpha'
   fi
+  if [[ -z "$tvk_ns" ]];then
+    tvk_ns="default"
+  fi
   get_ns=$(kubectl get deployments -l "release=triliovault-operator" -A 2>> >(logit) | awk '{print $1}' | sed -n 2p)
   if [ -z "$get_ns" ];then
+    #Create ns for installation, if not there.
+    ret=$(kubectl get ns $tvk_ns 2>/dev/null)
+    if [[ -z "$ret" ]]; then
+      if ! kubectl create ns $tvk_ns 2>> >(logit)
+      then
+        echo "$tvk_ns namespace creation failed"
+
+      fi
+    fi
     # Install triliovault operator
     echo "Installing Triliovault operator..."
-    helm install triliovault-operator triliovault-operator/k8s-triliovault-operator --version $operator_version 2>> >(logit)
+    helm install triliovault-operator triliovault-operator/k8s-triliovault-operator --version $operator_version -n $tvk_ns 2>> >(logit)
     retcode=$?
     if [ "$retcode" -ne 0 ];then 
       echo "There is some error in helm install triliovaul operator,please resolve and try again" 2>> >(logit) 
@@ -166,6 +179,7 @@ install_tvk()
       fi
     else
       upgrade_tvo=1
+      tvk_ns="$get_ns"
       echo "Upgrading Triliovault operator"
       semver=( ${old_operator_version//./ } )
       major="${semver[0]}"
@@ -181,7 +195,7 @@ install_tvk()
 	  return 1
         fi
       fi 	
-      helm  upgrade triliovault-operator triliovault-operator/k8s-triliovault-operator --version $operator_version 2>> >(logit)
+      helm upgrade triliovault-operator triliovault-operator/k8s-triliovault-operator --version $operator_version -n "$get_ns" 2>> >(logit)
       retcode=$?
       if [ "$retcode" -ne 0 ];then 
         echo "There is some error in helm upgrade,please resolve and try again" 2>> >(logit)
@@ -190,9 +204,9 @@ install_tvk()
       sleep 10
     fi
   fi
-  cmd="kubectl get pod -l release=triliovault-operator -o 'jsonpath={.items[*].status.conditions[*].status}' | grep -v False"
+  cmd="kubectl get pod -l release=triliovault-operator -n $tvk_ns -o 'jsonpath={.items[*].status.conditions[*].status}' | grep -v False"
   wait_install 10 "$cmd"
-  if ! kubectl get pods -l release=triliovault-operator 2>/dev/null | grep -q Running;then
+  if ! kubectl get pods -l release=triliovault-operator -n "$tvk_ns" 2>/dev/null | grep -q Running;then
     if [[ $upgrade_tvo == 1 ]];then
       echo "Triliovault operator upgrade failed"
     else
@@ -203,7 +217,7 @@ install_tvk()
   echo "Triliovault operator is running"
   
   #check if TVK manager is installed
-  if [[ $(kubectl get pods -l app=k8s-triliovault-control-plane 2>/dev/null) ]] && [[ $(kubectl get pods -l app=k8s-triliovault-admission-webhook 2>/dev/null) ]];then
+  if [[ $(kubectl get pods -l app=k8s-triliovault-control-plane -A 2>/dev/null) ]] && [[ $(kubectl get pods -l app=k8s-triliovault-admission-webhook 2>/dev/null) ]];then
     echo "Triliovault manager is already installed"
     if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
       exit 1
@@ -223,6 +237,7 @@ install_tvk()
     else
       echo "Upgrading triliovault manager.."
       tvm_upgrade=1
+      tvk_ns="$get_ns"
       if [[ $old_tvm_version == 2.1* ]] && [[ $new_triliovault_manager_version == 2.5* ]];
       then
         svc_type=$(kubectl get svc k8s-triliovault-ingress-gateway -o 'jsonpath={.spec.type}')
@@ -236,6 +251,7 @@ metadata:
   labels:
     triliovault: triliovault
   name: tvm
+  namespace: ${tvk_ns}
 spec:
   trilioVaultAppVersion: ${triliovault_manager_version}
   componentConfiguration:
@@ -269,6 +285,7 @@ metadata:
   labels:
     triliovault: triliovault
   name: tvm
+  namespace: ${tvk_ns}
 spec:
   trilioVaultAppVersion: ${triliovault_manager_version}
   helmVersion:
@@ -286,11 +303,11 @@ EOF
   else
     echo "Installing Triliovault manager...."
   fi
-  cmd="kubectl get pods -l app=k8s-triliovault-control-plane 2>/dev/null | grep Running"
+  cmd="kubectl get pods -l app=k8s-triliovault-control-plane -n $tvk_ns 2>/dev/null | grep Running"
   wait_install 10 "$cmd"
-  cmd="kubectl get pods -l app=k8s-triliovault-admission-webhook 2>/dev/null | grep Running"
+  cmd="kubectl get pods -l app=k8s-triliovault-admission-webhook -n $tvk_ns 2>/dev/null | grep Running"
   wait_install 10 "$cmd"
-  if ! kubectl get pods -l app=k8s-triliovault-control-plane 2>/dev/null | grep -q Running && ! kubectl get pods -l app=k8s-triliovault-admission-webhook 2>/dev/null | grep -q Running; then
+  if ! kubectl get pods -l app=k8s-triliovault-control-plane -n "$tvk_ns" 2>/dev/null | grep -q Running && ! kubectl get pods -l app=k8s-triliovault-admission-webhook -n "$tvk_ns" 2>/dev/null | grep -q Running; then
       if [[ $tvm_upgrade == 1 ]];then
         echo "TVM upgrade failed"
       else
@@ -303,13 +320,15 @@ EOF
   else
     echo "TVK Manager is installed"
   fi
-  install_license
+  install_license "$tvk_ns"
 }
 
 
 #This module is use to install license
 install_license(){
+  tvk_ns=$1
   echo "Installing Freetrial license..."
+  sleep 2
   cat <<EOF | python3
 #!/usr/bin/python3
 
@@ -329,9 +348,11 @@ soup = BeautifulSoup(contents, 'lxml')
 sys.stdout = open("license_file1.yaml", "w")
 print(soup.body.find('div', attrs={'class':'yaml-content'}).text)
 sys.stdout.close()
-result = subprocess.check_output("kubectl apply -f license_file1.yaml", shell=True)
+result = subprocess.check_output("kubectl apply -f license_file1.yaml -n $tvk_ns", shell=True)
 EOF
-  if ! kubectl get license 1>> >(logit) 2>> >(logit) | grep -q Activated;then
+  ret=$(kubectl get license -n "$tvk_ns" 2>> >(logit) | grep -q Activated)
+  ret_code=$?
+  if [ "$ret_code" -ne 0 ];then
     echo "License installation failed"
     exit 1
   else
