TVK UI config when tvk is installed on particular ns modifications

diff --git a/tvk-oneclick/tvk-oneclick b/tvk-oneclick/tvk-oneclick
--- a/tvk-oneclick/tvk-oneclick
+++ b/tvk-oneclick/tvk-oneclick
@@ -61,29 +61,13 @@ vercomp () {
     then
         return 0
     fi
-    local IFS=.
-    local i ver1=($1) ver2=($2)
-    # fill empty fields in ver1 with zeros
-    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
-    do
-        ver1[i]=0
-    done
-    for ((i=0; i<${#ver1[@]}; i++))
-    do
-        if [[ -z ${ver2[i]} ]]
-        then
-            # fill empty fields in ver2 with zeros
-            ver2[i]=0
-        fi
-        if ((10#${ver1[i]} > 10#${ver2[i]}))
-        then
-            return 1
-        fi
-        if ((10#${ver1[i]} < 10#${ver2[i]}))
-        then
-            return 2
-        fi
-    done
+    ret=$(python3 -c "from packaging import version;print(version.parse($1) < version.parse($2))")
+    if $ret;then
+      return 2
+    else
+      return 1
+    fi
+
     return 0
 }
 
@@ -163,6 +147,7 @@ install_tvk()
       return 1
     fi
   else
+    tvk_ns="$get_ns"
     echo "Triliovault operator is already installed!"
     if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
         exit 1
@@ -179,7 +164,6 @@ install_tvk()
       fi
     else
       upgrade_tvo=1
-      tvk_ns="$get_ns"
       echo "Upgrading Triliovault operator"
       semver=( ${old_operator_version//./ } )
       major="${semver[0]}"
@@ -222,6 +206,7 @@ install_tvk()
     if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
       exit 1
     fi
+    tvk_ns="$get_ns"
     #Check if TVM can be upgraded
     old_tvm_version=$(kubectl get TrilioVaultManager -n "$get_ns" -o json | grep releaseVersion | awk '{print$2}' | sed 's/[a-z-]//g' |  sed -e 's/^"//' -e 's/"$//')
     # shellcheck disable=SC2001
@@ -237,7 +222,6 @@ install_tvk()
     else
       echo "Upgrading triliovault manager.."
       tvm_upgrade=1
-      tvk_ns="$get_ns"
       if [[ $old_tvm_version == 2.1* ]] && [[ $new_triliovault_manager_version == 2.5* ]];
       then
         svc_type=$(kubectl get svc k8s-triliovault-ingress-gateway -o 'jsonpath={.spec.type}')
@@ -327,6 +311,9 @@ EOF
 #This module is use to install license
 install_license(){
   tvk_ns=$1
+  echo "Installing required packages.."
+  pip3 install beautifulsoup4 1>> >(logit) 2>> >(logit)
+  pip3 install lxml 1>> >(logit) 2>> >(logit)
   echo "Installing Freetrial license..."
   sleep 2
   cat <<EOF | python3
@@ -365,7 +352,7 @@ EOF
 configure_ui()
 {
  if  [[ -z ${input_config} ]];then
-   echo -e "TVK UI can be accessed using \n1.Loadbalancer \n2.Nodeport \n3.PortForwarding"
+   echo -e "TVK UI can be accessed using \n1.LoadBalancer \n2.NodePort \n3.PortForwarding"
    read -r -p "Please enter option: " ui_access_type
  else
    if [[ $ui_access_type == 'Loadbalancer' ]];then
@@ -384,8 +371,9 @@ configure_ui()
  fi
  case $ui_access_type in
    3)
-     echo "kubectl port-forward --address 0.0.0.0 svc/k8s-triliovault-ingress-gateway 80:80 &"
-     echo "The above command will start forwarding TVK management console traffic to the localhost IP of 127.0.0.1 via port 80"
+     get_ns=$(kubectl get deployments -l "release=triliovault-operator" -A 2>> >(logit) | awk '{print $1}' | sed -n 2p)
+     echo "kubectl port-forward --address 0.0.0.0 svc/k8s-triliovault-ingress-gateway -n $get_ns 80:80 &"
+     echo "Copy & paste the command above into your terminal session and TVK management console traffic will be forwarded to your localhost IP of 127.0.0.1 via port 80."
      ;;
    2)
      configure_nodeport_for_tvkui
@@ -408,24 +396,29 @@ configure_ui()
 configure_nodeport_for_tvkui()
 {
   if  [[ -z ${input_config} ]];then
-    read -r -p "Please enter host name for tvk ingress (default - tvk-doks): " tvkhost_name
+    read -r -p "Please enter host name for tvk ingress (default - tvk-doks.com): " tvkhost_name
   fi
   if [[ -z ${tvkhost_name} ]];then
-    tvkhost_name="tvk-doks"
+    tvkhost_name="tvk-doks.com"
   fi
-  gateway=$(kubectl get pods --no-headers=true 2>/dev/null | awk '/k8s-triliovault-ingress-gateway/{print $1}')
+  get_ns=$(kubectl get deployments -l "release=triliovault-operator" -A 2>> >(logit) | awk '{print $1}' | sed -n 2p)
+  gateway=$(kubectl get pods --no-headers=true -n "$get_ns" 2>/dev/null | awk '/k8s-triliovault-ingress-gateway/{print $1}')
   if [[ -z "$gateway" ]]; then
     echo "Not able to find k8s-triliovault-ingress-gateway resource,TVK UI configuration failed"
     return 1
   fi
-  node=$(kubectl get pods "$gateway" -o jsonpath='{.spec.nodeName}' 2>> >(logit))
-  ip=$(kubectl get node "$node"  -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}' 2>> >(logit))
-  port=$(kubectl get svc k8s-triliovault-ingress-gateway  -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}' 2>> >(logit))
-  if ! kubectl patch ingress k8s-triliovault-ingress-master -p '{"spec":{"rules":[{"host":"'"${tvkhost_name}"'"}]}}';then
+  node=$(kubectl get pods "$gateway" -n "$get_ns" -o jsonpath='{.spec.nodeName}' 2>> >(logit))
+  ip=$(kubectl get node "$node" -n "$get_ns" -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}' 2>> >(logit))
+  port=$(kubectl get svc k8s-triliovault-ingress-gateway -n "$get_ns" -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}' 2>> >(logit))
+  if ! kubectl patch ingress k8s-triliovault-ingress-master -n "$get_ns" -p '{"spec":{"rules":[{"host":"'"${tvkhost_name}"'"}]}}';then
     echo "TVK UI configuration failed, please check ingress"
     return 1
   fi
-  echo "For accesing UI, create an entry in /etc/hosts file for the IPs like '$ip  $tvkhost_name'"
+  if ! kubectl patch svc k8s-triliovault-ingress-gateway -n "$get_ns" -p '{"spec": {"type": "NodePort"}}' 1>> >(logit) 2>> >(logit) ; then
+    echo "TVK UI configuration failed, please check ingress"
+    return 1
+  fi
+  echo "Please add '$ip $tvkhost_name' entry to your /etc/host file before launching the console"
   echo "After creating an entry,TVK UI can be accessed through http://$tvkhost_name:$port/login"
   echo "For https access, please refer - https://docs.trilio.io/kubernetes/management-console/user-interface/accessing-the-ui" 
 }
@@ -443,31 +436,43 @@ configure_loadbalancer_for_tvkUI()
     echo "To use DigitalOcean DNS, you need to register a domain name with a registrar and update your domain’s NS records to point to DigitalOcean’s name servers."
     read -r -p "Please enter domainname for cluster(Domain name you have registered and added in Doks console): " domain
     read -r -p "Please enter host name for tvk ingress (default - tvk-doks): " tvkhost_name
+    read -r -p "Please enter auth token for doctl: " doctl_token
+  fi
+  if [[ -z ${doctl_token} ]];then
+    echo "This functionality requires Digital Ocean authentication token"
+    return 1
   fi
   if [[ -z ${tvkhost_name} ]];then
     tvkhost_name="tvk-doks"
   fi
+  ret=$(doctl auth init -t $doctl_token)
+  ret_code=$?
+  if [ "$ret_code" -ne 0 ];then
+    echo "Cannot authenticate with the provided doctl auth token"
+    return 1
+  fi
+  get_ns=$(kubectl get deployments -l "release=triliovault-operator" -A 2>> >(logit) | awk '{print $1}' | sed -n 2p)
   cluster_name=$(kubectl config view --minify -o jsonpath='{.clusters[].name}' | cut -d'-' -f3-)
   if [[ -z ${cluster_name} ]];then
     echo "Error in getting cluster name from the current-context set in kubeconfig"
     echo "Please check the current-context"
     return 1
   fi
-  if ! kubectl patch svc k8s-triliovault-ingress-gateway -p '{"spec": {"type": "LoadBalancer"}}' 1>> >(logit) 2>> >(logit) ; then
+  if ! kubectl patch svc k8s-triliovault-ingress-gateway -n "$get_ns" -p '{"spec": {"type": "LoadBalancer"}}' 1>> >(logit) 2>> >(logit) ; then
     echo "TVK UI configuration failed, please check ingress"
     return 1
   fi
   echo "Configuring UI......This may take some time"
-  cmd="kubectl get svc k8s-triliovault-ingress-gateway -o 'jsonpath={.status.loadBalancer}'"
+  cmd="kubectl get svc k8s-triliovault-ingress-gateway -n $get_ns -o 'jsonpath={.status.loadBalancer}'"
   wait_install 20 "$cmd"
-  val_status=$(kubectl get svc k8s-triliovault-ingress-gateway -o 'jsonpath={.status.loadBalancer}')
+  val_status=$(kubectl get svc k8s-triliovault-ingress-gateway -n "$get_ns" -o 'jsonpath={.status.loadBalancer}')
   if [[ $val_status == '{}' ]]
   then
     echo "Loadbalancer taking time to get External IP"
     return 1
   fi
-  external_ip=$(kubectl get svc k8s-triliovault-ingress-gateway -o 'jsonpath={.status.loadBalancer.ingress[0].ip}' 2>> >(logit))
-  kubectl patch ingress k8s-triliovault-ingress-master -p '{"spec":{"rules":[{"host":"'"${tvkhost_name}.${domain}"'"}]}}' 1>> >(logit) 2>> >(logit)
+  external_ip=$(kubectl get svc k8s-triliovault-ingress-gateway -n "$get_ns" -o 'jsonpath={.status.loadBalancer.ingress[0].ip}' 2>> >(logit))
+  kubectl patch ingress k8s-triliovault-ingress-master -n "$get_ns" -p '{"spec":{"rules":[{"host":"'"${tvkhost_name}.${domain}"'"}]}}' 1>> >(logit) 2>> >(logit)
   doctl compute domain records create "${domain}" --record-type A --record-name "${tvkhost_name}" --record-data "${external_ip}" 1>> >(logit) 2>> >(logit)
   retCode=$?
   if [[ "$retCode" -ne 0 ]]; then
@@ -771,10 +776,10 @@ create_aws_s3()
   fi
   call_s3cfg_aws "$access_key" "$secret_key" "$host_base" "$host_bucket" "$bucket_location"
   #create bucket
-  ret_val=$(s3cmd --config s3cfg_config mb s3://"$bucket_name" 2>> >(logit))
+  ret_val=$(s3cmd --config s3cfg_config mb s3://"$bucket_name" 2>&1)
   ret_mgs=$?
   if [[ "$ret_mgs" -ne 0 ]];then
-    ret_code=$(echo "$ret_val" | grep 'Bucket already exists')
+    ret_code=$(echo "$ret_val" | grep 'BucketAlreadyOwnedByYou')
     if [[ "$ret_code" ]]; then
       echo "WARNING: Bucket already exists"
     else
@@ -956,6 +961,11 @@ sample_test()
    res=$(kubectl get ns $backup_namespace 2>/dev/null)
    if [[ -z "$res" ]]; then
      kubectl create ns $backup_namespace 2>/dev/null
+   fi
+   storage_class=$(kubectl get storageclass | grep -w '(default)' | awk  '{print $1}')
+   if [[ -z "$storage_class" ]];then
+     echo "No default storage class found, need one to proceed";
+     return 1
    fi
    #Add stable helm repo
    helm repo add stable https://charts.helm.sh/stable 1>> >(logit) 2>> >(logit)
@@ -1437,5 +1447,17 @@ if [[ -z $ret ]];then
   echo "Plugin requires python3 installed"
   echo "Please install and check"
   return 1
+fi
+ret=$(pip3 --version 2>> >(logit))
+ret_code=$?
+if [ "$ret_code" -ne 0 ];then
+  echo "This plugin requires pip3 to be installed.Please follow README"
+  exit 1
+fi
+ret=$(pip3 install packaging 1>> >(logit) 2>> >(logit))
+ret_code=$?
+if [ "$ret_code" -ne 0 ];then
+  echo "pip3 install is failing..Please check the permisson and try again.."
+  exit 1
 fi
 main "$@"
