rke related changes

diff --git a/tvk-oneclick/tvk-oneclick b/tvk-oneclick/tvk-oneclick
--- a/tvk-oneclick/tvk-oneclick
+++ b/tvk-oneclick/tvk-oneclick
@@ -2,12 +2,12 @@
 
 #This program is use to install/configure/test TVK product with one click and few required inputs
 
-#This module is used to perform preflight check which checks if all the pre-requisites are satisfied before installing Triliovault for Kubernetes application in a Kubernetes cluster
 masterIngName=k8s-triliovault-master
 ingressGateway=k8s-triliovault-ingress-gateway
 operatorSA=triliovault-operator-k8s-triliovault-operator-service-account
 tvkmanagerSA=k8s-triliovault
 
+#This module is used to perform preflight check which checks if all the pre-requisites are satisfied before installing Triliovault for Kubernetes application in a Kubernetes cluster
 preflight_checks() {
   ret=$(kubectl krew 2>/dev/null)
   if [[ -z "$ret" ]]; then
@@ -162,14 +162,16 @@ install_tvk() {
       return 1
     fi
     if [ "$open_flag" -eq 1 ]; then
-      while true; do
-        kubectl get sa $operatorSA -n $tvk_ns 2>> >(logit) 1>> >(logit)
-        if [[ $? == 0 ]];then
-          kubectl get sa -n "$tvk_ns" | sed -n '1!p' | awk '{print $1, $8}' | sed 's/ //g' | xargs -I '{}' oc adm policy add-scc-to-user anyuid -z '{}' -n "$tvk_ns" 1>> >(logit) 2>> >(logit)
-         kubectl get sa -n "$tvk_ns" | sed -n '1!p' | awk '{print $1, $8}' | sed 's/ //g' | xargs -I '{}' oc adm policy add-cluster-role-to-user cluster-admin  -z '{}' -n "$tvk_ns" 1>> >(logit) 2>> >(logit)
-	 break
-        fi
-      done
+      cmd="kubectl get sa $operatorSA -n $tvk_ns 2>> >(logit)"
+      wait_install 10 "$cmd"
+      kubectl get sa $operatorSA -n $tvk_ns 2>> >(logit) 1>> >(logit)
+      if [[ $? == 0 ]];then
+        kubectl get sa -n "$tvk_ns" | sed -n '1!p' | awk '{print $1, $8}' | sed 's/ //g' | xargs -I '{}' oc adm policy add-scc-to-user anyuid -z '{}' -n "$tvk_ns" 1>> >(logit) 2>> >(logit)
+        kubectl get sa -n "$tvk_ns" | sed -n '1!p' | awk '{print $1, $8}' | sed 's/ //g' | xargs -I '{}' oc adm policy add-cluster-role-to-user cluster-admin  -z '{}' -n "$tvk_ns" 1>> >(logit) 2>> >(logit)
+      else
+	echo "Something wrong when assigning privilege to Trilio operator SA"
+	exit 1
+      fi
     fi
     get_ns=$(kubectl get deployments -l "release=triliovault-operator" -A 2>> >(logit) | awk '{print $1}' | sed -n 2p)
   else
@@ -311,14 +313,16 @@ EOF
       tvm_upgrade=1
     elif [[ $ret_val1 == 2 ]] || [[ $ret_val1 == 1 ]]; then
       if [ "$open_flag" -eq 1 ]; then
-        while true; do
-          kubectl get sa $tvkmanagerSA -n $tvk_ns 2>> >(logit) 1>> >(logit)
-          if [[ $? == 0 ]];then
-            kubectl get sa -n "$tvk_ns" | sed -n '1!p' | awk '{print $1, $8}' | sed 's/ //g' | xargs -I '{}' oc adm policy add-scc-to-user anyuid -z '{}' -n "$tvk_ns" 1>> >(logit) 2>> >(logit)
-           kubectl get sa -n "$tvk_ns" | sed -n '1!p' | awk '{print $1, $8}' | sed 's/ //g' | xargs -I '{}' oc adm policy add-cluster-role-to-user cluster-admin  -z '{}' -n "$tvk_ns" 1>> >(logit) 2>> >(logit)
-           break
-          fi
-        done
+        cmd="kubectl get sa $tvkmanagerSA -n $tvk_ns 2>> >(logit)"
+        wait_install 10 "$cmd"
+        kubectl get sa $tvkmanagerSA -n $tvk_ns 2>> >(logit) 1>> >(logit)
+        if [[ $? == 0 ]];then
+          kubectl get sa -n "$tvk_ns" | sed -n '1!p' | awk '{print $1, $8}' | sed 's/ //g' | xargs -I '{}' oc adm policy add-scc-to-user anyuid -z '{}' -n "$tvk_ns" 1>> >(logit) 2>> >(logit)
+          kubectl get sa -n "$tvk_ns" | sed -n '1!p' | awk '{print $1, $8}' | sed 's/ //g' | xargs -I '{}' oc adm policy add-cluster-role-to-user cluster-admin  -z '{}' -n "$tvk_ns" 1>> >(logit) 2>> >(logit)
+        else
+          echo "Something wrong when assigning privilege to Trilio operator SA"
+          exit 1
+        fi
       fi
       echo "Waiting for Pods to come up.."
       sleep 10
@@ -661,7 +665,7 @@ configure_ui() {
   kubectl get crd openshiftcontrollermanagers.operator.openshift.io 1>> >(logit) 2>> >(logit)
   ret_val=$?
   open_flag=0
-  if [ "$ret_code" -eq 0 ]; then
+  if [ "$ret_val" -eq 0 ]; then
     oc -n openshift-ingress-operator patch ingresscontroller/default --patch '{"spec":{"routeAdmission":{"namespaceOwnership":"InterNamespaceAllowed"}}}' --type=merge
   fi
   get_node=$(kubectl get nodes | awk 'NR==2{print $1}')
@@ -835,11 +839,13 @@ configure_loadbalancer_for_tvkUI() {
     tvk_name=$tvkhost_name    
   fi
   get_ns=$(kubectl get deployments -l "release=triliovault-operator" -A 2>> >(logit) | awk '{print $1}' | sed -n 2p)
-  cluster_name=$(kubectl config view --minify -o jsonpath='{.clusters[].name}' | cut -d'-' -f3-)
-  if [[ -z ${cluster_name} ]]; then
-    echo "Error in getting cluster name from the current-context set in kubeconfig"
-    echo "Please check the current-context"
-    return 1
+  if [[ $do -eq "True" ]]; then
+    cluster_name=$(kubectl config view --minify -o jsonpath='{.clusters[].name}' | cut -d'-' -f3-)
+    if [[ -z ${cluster_name} ]]; then
+      echo "Error in getting cluster name from the current-context set in kubeconfig"
+      echo "Please check the current-context"
+      return 1
+    fi
   fi
   # Getting tvm version and setting the configs accordingly
   tvm_name=$(kubectl get tvm -A | awk '{print $2}' | sed -n 2p)
@@ -895,7 +901,17 @@ EOF
     echo "Loadbalancer taking time to get External IP"
     return 1
   fi
+  #set -x
   external_ip=$(kubectl get svc "$ingressGateway" -n "$get_ns" -o 'jsonpath={.status.loadBalancer.ingress[0].ip}' 2>> >(logit))
+  if [[ -z "$external_ip" ]]; then
+    hostname=$(kubectl get svc "$ingressGateway" -n "$get_ns" -o 'jsonpath={.status.loadBalancer.ingress[0].hostname}' 2>> >(logit))
+    if [[ -z "$hostname" ]]; then 
+      echo "ExternalIP is not set, please check configurations"
+      return 1
+    fi
+    external_ip=$(dig a4acb73d911624f8fa61dc339209a2da-588655396.us-east-1.elb.amazonaws.com +short | awk 'NR==2 {print $1}' 2>> >(logit))
+   # Do what you want
+  fi
   if [[ $ret_val != 2 ]] && [[ $ret_val != 1 ]]; then
     kubectl patch ingress k8s-triliovault-ingress-master -n "$get_ns" -p '{"spec":{"rules":[{"host":"'"${tvkhost_name}.${domain}"'"}]}}' 1>> >(logit) 2>> >(logit)
   fi
@@ -1125,7 +1141,9 @@ create_doks_s3() {
     if [[ "$ret_code" ]] || [[ $ret_code_err ]]; then
       echo "WARNING: Bucket already exists"
     else
+      echo "$ret_mgs"
       echo "Error in creating spaces,please check credentials"
+      exit 1
     fi
   fi
   #create S3 target
@@ -1284,13 +1302,19 @@ create_aws_s3() {
   #create bucket
   ret_val=$(s3cmd --config s3cfg_config mb s3://"$bucket_name" 2>&1)
   ret_mgs=$?
+
   if [[ "$ret_mgs" -ne 0 ]]; then
     ret_code=$(echo "$ret_val" | grep 'BucketAlreadyOwnedByYou')
+    ret_code1=$(echo "$ret_val" | grep 'BucketNameUnavailable')
     if [[ "$ret_code" ]]; then
       echo "WARNING: Bucket already exists"
+    elif [[ "$ret_code1" ]]; then
+      echo "WARNING: Bucket Name unavailable,please use different name"
+      exit 1
     else
-      echo "Error in creating bucket,please check credentials"
-      return 1
+      echo "$ret_val"
+      echo "Error in creating bucket,please check credentials/name"
+      exit 1
     fi
   fi
   #create S3 target
@@ -1331,6 +1355,7 @@ EOF
 
 #create readymade Minio server and create target
 create_readymade_minio() {
+  echo "Minio requires sufficient memory.So please check memory and then configure"
   if [[ -z ${input_config} ]]; then
     read -r -p "Minio server Namespace (minio): " minio_server_namespace
     read -r -p "Bucket Name: (tvk-target): " bucket_name
@@ -1480,7 +1505,7 @@ create_readymade_minio() {
       echo "WARNING: Bucket already exists"
     else
       echo "Error in creating bucket,please check credentials"
-      return 1
+      exit 1
     fi
   fi
   kubectl delete pod -n "$minio_server_namespace" "$mc_pod_nm" 1>> >(logit) 2>> >(logit)
@@ -1563,6 +1588,7 @@ create_gcp_s3() {
   if [[ -z "$bucket_location" ]]; then
     bucket_location="us-east-1"
   fi
+
   url="https://storage.googleapis.com"
   check_target_existence "$target_name" "$target_namespace" "$access_key" "$secret_key" "$url" "$bucket_name" "$bucket_location"
   ret_code=$?
@@ -1575,11 +1601,16 @@ create_gcp_s3() {
   ret_mgs=$?
   if [[ "$ret_mgs" -ne 0 ]]; then
     ret_code=$(echo "$ret_val" | grep 'BucketAlreadyOwnedByYou')
+    ret_code1=$(echo "$ret_val" | grep 'BucketNameUnavailable')
     if [[ "$ret_code" ]]; then
       echo "WARNING: Bucket already exists"
+    elif [[ "$ret_code1" ]]; then
+      echo "WARNING: Bucket Name unavailable,please use different name"
+      exit 1
     else
-      echo "Error in creating bucket,please check credentials"
-      return 1
+      echo "$ret_val"
+      echo "Error in creating bucket,please check credentials/name"
+      exit 1
     fi
   fi
   #create S3 target
