Added upgrade logic

diff --git a/tvk-oneclick/tvk-oneclick b/tvk-oneclick/tvk-oneclick
--- a/tvk-oneclick/tvk-oneclick
+++ b/tvk-oneclick/tvk-oneclick
@@ -4,9 +4,7 @@
 #This program is use to install/configure/test TVK product with one click and few required inputs
 
 
-
 #This module is used to perform preflight check which checks if all the pre-requisites are satisfied before installing Triliovault for Kubernetes application in a Kubernetes cluster
-
 preflight_checks()
 {
   ret=$(kubectl krew 2>/dev/null)
@@ -26,7 +24,6 @@ preflight_checks()
   if  [[ -z "${input_config}" ]];then
     read -r -p "Provide storageclass to be used for TVK/Application Installation(storageclass with default annotation): " storage_class
   fi
-  #read -p "Provide storageclass to be used for TVK/Application Installation(storageclass with default annotation): " storage_class
   if [[ -z "$storage_class" ]];then
 	  storage_class=$(kubectl get storageclass | grep -w '(default)' | awk  '{print $1}')
   fi
@@ -43,8 +40,40 @@ preflight_checks()
       exit 1
     fi
   fi
-
 }
+
+#This function is use to compare 2 versions
+vercomp () {
+    if [[ $1 == $2 ]]
+    then
+        return 0
+    fi
+    local IFS=.
+    local i ver1=($1) ver2=($2)
+    # fill empty fields in ver1 with zeros
+    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
+    do
+        ver1[i]=0
+    done
+    for ((i=0; i<${#ver1[@]}; i++))
+    do
+        if [[ -z ${ver2[i]} ]]
+        then
+            # fill empty fields in ver2 with zeros
+            ver2[i]=0
+        fi
+        if ((10#${ver1[i]} > 10#${ver2[i]}))
+        then
+            return 1
+        fi
+        if ((10#${ver1[i]} < 10#${ver2[i]}))
+        then
+            return 2
+        fi
+    done
+    return 0
+}
+
 
 
 #function to print waiting symbol
@@ -79,8 +108,11 @@ install_tvk()
   helm repo update >/dev/null 2>/dev/null
   if  [[ -z ${input_config} ]];then
     read -r -p "Please provide the operator version to be installed(2.1.0): " operator_version
-    read  -r -p "Please provide the triliovault manager version(v2.1.1-alpha): " triliovault_manager_version
-    read  -r -p "if resource exist, still user wants to proceed: " if_resource_exists_still_proceed
+    read -r -p "Please provide the triliovault manager version(v2.1.1-alpha): " triliovault_manager_version
+    read -r -p "Proceed even if resource exists(True): " if_resource_exists_still_proceed
+  fi
+  if [[ -z "$if_resource_exists_still_proceed" ]];then
+    if_resource_exists_still_proceed=True
   fi
   if [[ -z "$operator_version" ]];then
     operator_version='2.1.0'
@@ -88,36 +120,58 @@ install_tvk()
   if [[ -z "$triliovault_manager_version" ]];then
     triliovault_manager_version='v2.1.1-alpha'
   fi
-  #check if TVK operator already exists
-  if [[ $(kubectl get pods -l release=triliovault-operator 2>/dev/null) ]];then  
-    echo "TVK operator already exists"
-    if ! [[ $if_resource_exists_still_proceed ]];then
-  	exit 1
-    fi
-  else
+  get_ns=$(kubectl get svc -A | grep -w triliovault-operator-k8s-triliovault-operator-webhook-service | awk '{print $1}')
+  if [ -z "$get_ns" ];then
     # Install triliovault operator
     echo "Installing Triliovault operator..."
-    helm install triliovault-operator triliovault-operator/k8s-triliovault-operator --version $operator_version 2>/dev/null 
-    cmd="kubectl get pods -l release=triliovault-operator 2>/dev/null | grep Running"
-    wait_install "10 minute" "$cmd"
-    if ! kubectl get pods -l release=triliovault-operator 2>/dev/null | grep -q Running;then
-      echo "TVO installation failed"
-      exit 1
+    helm install triliovault-operator triliovault-operator/k8s-triliovault-operator --version $operator_version 2>/dev/null
+  else
+    old_operator_version=$(helm list  -n $get_ns | grep k8s-triliovault-operator | awk '{print $9}' | rev  | cut -d- -f1 | rev | sed 's/[a-z-]//g')
+    new_operator_version=$(echo $operator_version | sed 's/[a-z-]//g')
+    vercomp $old_operator_version $new_operator_version
+    ret_val=$?
+    if [[ $ret_val != 2 ]];then
+      echo "Triliovault operator cannot be upgraded, please check version number"
+      if ! [[ $if_resource_exists_still_proceed ]];then
+        exit 1
+      fi
+    else
+      echo "Upgrading Triliovault operator"
+      semver=( ${old_operator_version//./ } )
+      major="${semver[0]}"
+      minor="${semver[1]}"
+      patch="${semver[2]}"
+      sub_ver=${major}.${minor}
+      if [[ $sub_ver == 2.0 ]];then
+        helm plugin install https://github.com/trilioData/tvm-helm-plugins >/dev/null 2>/dev/null
+	rel_name=$(helm list | grep k8s-triliovault-operator | awk '{print $1}')
+	helm tvm-upgrade --release=$rel_name --namespace=$get_ns 2>/dev/null
+      fi 	
+      helm  upgrade triliovault-operator triliovault-operator/k8s-triliovault-operator --version $operator_version 2>/dev/null
+      sleep 10
     fi
-    echo "Triliovault operator is installed"
   fi
+  cmd="kubectl get pod -l release=triliovault-operator -o 'jsonpath={.items[*].status.conditions[*].status}' | grep -v False"
+  wait_install "10 minute" "$cmd"
+  if ! kubectl get pods -l release=triliovault-operator 2>/dev/null | grep -q Running;then
+    echo "TVO installation failed"
+    exit 1
+  fi
+  echo "Triliovault operator is installed"
+  
   #check if TVK manager is installed
   if [[ $(kubectl get pods -l app=k8s-triliovault-control-plane 2>/dev/null) ]] && [[ $(kubectl get pods -l app=k8s-triliovault-admission-webhook 2>/dev/null) ]];then
-    echo "TVK Manager is already exists"
-    echo "Checking if TVK manager is of required version.."
-    tvm=$(kubectl get TrilioVaultManager -o json | grep releaseVersion | awk '{print$2}')
-    tvm=$(sed -e 's/^"//' -e 's/"$//' <<<"$tvm")
-    if [[ $tvm == "$triliovault_manager_version" ]];then
-      echo "Triliovault manager/application of required version is already installed"
-      return
-    fi
-    if ! [[ $if_resource_exists_still_proceed ]];then
+    #Check if TVM can be upgraded
+    old_tvm_version=$(kubectl get TrilioVaultManager -n $get_ns -o json | grep releaseVersion | awk '{print$2}' | sed 's/[a-z-]//g' |  sed -e 's/^"//' -e 's/"$//')
+    new_triliovault_manager_version=$(echo $triliovault_manager_version | sed 's/[a-z-]//g')
+    vercomp $old_tvm_version $new_triliovault_manager_version
+    ret_val=$?
+    if [[ $ret_val != 2 ]];then
+      echo "TVM cannot be upgraded! Please check version"
+      if ! [[ $if_resource_exists_still_proceed ]];then
         exit 1
+      fi
+      return
     fi
   fi
     
@@ -180,9 +234,6 @@ print(soup.body.find('div', attrs={'class':'yaml-content'}).text)
 sys.stdout.close()
 result = subprocess.check_output("kubectl apply -f license_file1.yaml", shell=True)
 EOF
-  #install trilio license
-  #install_license.py
-
 }
 
 
@@ -235,11 +286,18 @@ configure_nodeport_for_tvkui()
   if  [[ -z ${input_config} ]];then
     read -r -p "Please enter hostname for a cluster: " tvkhost_name
   fi
-  gateway=$(kubectl get pods --no-headers=true | awk '/k8s-triliovault-ingress-gateway/{print $1}')
+  gateway=$(kubectl get pods --no-headers=true 2>/dev/null | awk '/k8s-triliovault-ingress-gateway/{print $1}')
+  if [[ -z "$gateway" ]]; then
+    echo "Not able to find k8s-triliovault-ingress-gateway resource,TVK UI configuration failed"
+    exit 1
+  fi
   node=$(kubectl get pods "$gateway" -o jsonpath='{.spec.nodeName}')
   ip=$(kubectl get node "$node"  -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}')
   port=$(kubectl get svc k8s-triliovault-ingress-gateway  -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}')
-  kubectl patch ingress k8s-triliovault-ingress-master -p '{"spec":{"rules":[{"host":"'"${tvkhost_name}-tvk.com"'"}]}}'
+  if ! kubectl patch ingress k8s-triliovault-ingress-master -p '{"spec":{"rules":[{"host":"'"${tvkhost_name}-tvk.com"'"}]}}';then
+    echo "TVK UI configuration failed, please check ingress"
+    exit 1
+  fi
   echo "For accesing UI, create an entry in /etc/hosts file for the IPs like '$ip  $tvkhost_name-tvk.com'"
   echo "After creating an entry,TVK UI can be accessed through http://$tvkhost_name-tvk.com:$port"
   echo "For https access, please refer - https://docs.trilio.io/kubernetes/management-console/user-interface/accessing-the-ui" 
@@ -252,6 +310,10 @@ configure_loadbalancer_for_tvkUI()
    read -r -p "Please enter domainname for cluster: " domain
    read -r -p "Please enter host name  for a cluster: " tvkhost_name
    read -r -p "Please enter cluster name: " cluster_name 
+ fi
+ if ! kubectl patch svc k8s-triliovault-ingress-gateway -p '{"spec": {"type": "LoadBalancer"}}' >/dev/null 2>/dev/null ; then
+   echo "TVK UI configuration failed, please check ingress"
+   exit 1
  fi
  kubectl patch svc k8s-triliovault-ingress-gateway -p '{"spec": {"type": "LoadBalancer"}}' >/dev/null 2>/dev/null
  echo "Configuring UI......This may take some time"
@@ -393,7 +455,10 @@ EOM
           read -r -p "Target Name: " target_name
           read -r -p "Target Namespace: " target_namespace
 	  read -r -p "thresholdCapacity(1000Gi): " thresholdCapacity
-	  read -r -p "if resource exist, still user wants to proceed: " if_resource_exists_still_proceed
+	  read -r -p "Proceed even if resource exists(True): " if_resource_exists_still_proceed
+        fi
+	if [[ -z "$if_resource_exists_still_proceed" ]];then
+          if_resource_exists_still_proceed=True
         fi
 	if [[ $(kubectl get target "$target_name" -n "$target_namespace" 2>/dev/null) ]];
         then
@@ -458,9 +523,12 @@ EOF
           read -r -p "namespace: " target_namespace
           read -r -p "Export Path: " nfs_path
           read -r -p "NFSoption(nfsvers=4): " nfs_options
-          read -r -p "thresholdCapacity(100Gi): " thresholdCapacity
-	  read -r -p "if resource exist, still user wants to proceed: " if_resource_exists_still_proceed
+          read -r -p "thresholdCapacity(1000Gi): " thresholdCapacity
+	  read -r -p "Proceed even if resource exists(True): " if_resource_exists_still_proceed
 	fi
+        if [[ -z "$if_resource_exists_still_proceed" ]];then
+          if_resource_exists_still_proceed=True
+        fi
 	if [[ $(kubectl get target "$target_name" -n "$target_namespace" 2>/dev/null) ]];
         then
           echo "Target with same name already exists"
@@ -478,7 +546,8 @@ EOF
           nfs_options='nfsvers=4'
         fi
 	echo "Creating target..."
-	cat <<EOF | kubectl apply -f - &>/dev/null
+	cat <<EOF | kubectl apply -f - &>/dev/null 
+apiVersion: triliovault.trilio.io/v1
 kind: Target
 metadata:
   name: ${target_name}
@@ -520,7 +589,10 @@ sample_test()
      read -r -p "Backupplan name(trilio-test-backup): " bk_plan_name
      read -r -p "Backup Name(trilio-test-backup): " backup_name
      read -r -p "Backup Namespace Name(trilio-test-backup): " backup_namespace
-     read -r -p "if resource exist, still user wants to proceed: " if_resource_exists_still_proceed
+     read -r -p "Proceed even if resource exists(True): " if_resource_exists_still_proceed
+   fi
+   if [[ -z "$if_resource_exists_still_proceed" ]];then
+      if_resource_exists_still_proceed=True
    fi
    if [[ -z "$backup_namespace" ]]; then
       backup_namespace=trilio-test-backup
@@ -706,7 +778,7 @@ EOM
           spin='-\|/'
           i=0
           endtime=$(date -ud "$runtime" +%s)
-	  while [[ $(date -u +%s) -le $endtime ]] && kubectl get pod -l app.kubernetes.io/name=mongodb -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].stat}" | grep -w False
+	  while [[ $(date -u +%s) -le $endtime ]] && kubectl get pod -l app.kubernetes.io/name=mongodb -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -w False
           do
             i=$(( (i+1) %4 ))
             printf "\r %s" "${spin:$i:1}"
