some preflight cosmetic changes

diff --git a/tvk-oneclick/tvk-oneclick b/tvk-oneclick/tvk-oneclick
--- a/tvk-oneclick/tvk-oneclick
+++ b/tvk-oneclick/tvk-oneclick
@@ -13,7 +13,8 @@ preflight_checks()
     echo "https://krew.sigs.k8s.io/docs/user-guide/setup/install/"
     return 1
   fi
-  if  [[ $(kubectl tvk-preflight --help  2>/dev/null) ]];
+  ret=$(kubectl tvk-preflight --help  2>/dev/null)
+  if [[ ! -z "$ret" ]];
   then
     echo "Skipping plugin tvk-preflight installation as it is already installed"
   else
@@ -36,6 +37,10 @@ preflight_checks()
           fi
   fi
   check=$(kubectl tvk-preflight --storageclass "$storage_class" | tee /dev/tty)
+  ret_code=$?
+  if [ "$ret_code" -ne 0 ];then
+    echo "Failed to run 'kubectl tvk-preflight',please check if PATH variable for krew is set properly and then try"
+  fi
   check_for_fail=$(echo "$check" | grep  'Some Pre-flight Checks Failed!')
   if [[ -z "$check_for_fail" ]];then
     echo "All preflight checks are done and you can proceed"
