Preflight upgrade code with minor cosmetics changes

diff --git a/tvk-oneclick/tvk-oneclick b/tvk-oneclick/tvk-oneclick
--- a/tvk-oneclick/tvk-oneclick
+++ b/tvk-oneclick/tvk-oneclick
@@ -16,7 +16,12 @@ preflight_checks()
   ret=$(kubectl tvk-preflight --help  2>/dev/null)
   if [[ ! -z "$ret" ]];
   then
-    echo "Skipping plugin tvk-preflight installation as it is already installed"
+    echo "Skipping/Upgrading plugin tvk-preflight installation as it is already installed"
+    kubectl krew upgrade tvk-preflight 2>> >(logit)
+    retcode=$?
+    if [ "$retcode" -ne 0 ];then
+      echo "Failed to uggrade tvk-plugins/tvk-preflight plugin"
+    fi
   else
     plugin_url='https://github.com/trilioData/tvk-plugins.git'
     kubectl krew index add tvk-plugins "$plugin_url" 1>> >(logit) 2>> >(logit)
@@ -211,7 +216,7 @@ install_tvk()
     if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
       exit 1
     fi
-    tvm_name=$(kubectl get tvm | awk '{print $1}' | sed -n 2p)
+    tvm_name=$(kubectl get tvm -A | awk '{print $1}' | sed -n 2p)
     tvk_ns="$get_ns"
     #Check if TVM can be upgraded
     old_tvm_version=$(kubectl get TrilioVaultManager -n "$get_ns" -o json | grep releaseVersion | awk '{print$2}' | sed 's/[a-z-]//g' |  sed -e 's/^"//' -e 's/"$//')
@@ -320,19 +325,29 @@ EOF
 #This module is use to install license
 install_license(){
   tvk_ns=$1
+  ret=$(kubectl get license -n "$tvk_ns" 2>> >(logit) | grep -q Active)
+  ret_code=$?
+  ret_A=$(kubectl get license -A 2>> >(logit) | grep -q Active)
+  ret_code_A=$?
+  if [ "$ret_code" -eq 0 ] || [ "$ret_code_A" -eq 0 ];then
+    echo "License is already installed and is in active state"
+    return
+  fi
   echo "Installing required packages.."
-  pip3 install requests 1>> >(logit) 2>> >(logit)
-  pip3 install beautifulsoup4 1>> >(logit) 2>> >(logit)
-  pip3 install lxml 1>> >(logit) 2>> >(logit)
+  {
+    pip3 install requests
+    pip3 install beautifulsoup4
+    pip3 install lxml
+  } 1>> >(logit) 2>> >(logit)
   echo "Installing Freetrial license..."
   cat <<EOF | python3
 #!/usr/bin/python3
-
 from bs4 import BeautifulSoup
-import requests
 import sys
 import subprocess
-
+import warnings
+warnings.filterwarnings("ignore")
+import requests
 headers = {'Content-type': 'application/x-www-form-urlencoded; charset=utf-8'}
 endpoint="https://doc.trilio.io:5000/8d92edd6-514d-4acd-90f6-694cb8d83336/0061K00000fwkzU"
 result = subprocess.check_output("kubectl get ns kube-system -o=jsonpath='{.metadata.uid}'", shell=True)
@@ -616,9 +631,18 @@ create_doks_s3()
   if [[ -z "$if_resource_exists_still_proceed" ]];then
     if_resource_exists_still_proceed='y'
   fi
+  if [[ -z "$target_namespace" ]];then
+    target_namespace="default"
+  fi
   if [[ $(kubectl get target "$target_name" -n "$target_namespace" 2>> >(logit)) ]];
   then
-    echo "Target with same name already exists"
+    if kubectl get target "$target_name"  -n  "$target_namespace" -o 'jsonpath={.status.status}' 2>/dev/null | grep -q Unavailable; then
+      echo "Target with same name already exists but is in Unavailable state"
+      return 1
+    else
+      echo "Target with same name already exists"
+      return 0
+    fi
     if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
       exit 1
     else
@@ -774,9 +798,19 @@ create_aws_s3()
   if [[ -z "$if_resource_exists_still_proceed" ]];then
     if_resource_exists_still_proceed='y'
   fi
+  if [[ -z "$target_namespace" ]];then
+    target_namespace="default"
+  fi
   if [[ $(kubectl get target "$target_name" -n "$target_namespace" 2>> >(logit)) ]];
   then
-    echo "Target with same name already exists"
+    if kubectl get target "$target_name"  -n  "$target_namespace" -o 'jsonpath={.status.status}' 2>/dev/null | grep -q Unavailable; then
+      echo "Target with same name already exists but is in Unavailable state"
+      return 1
+    else
+      echo "Target with same name already exists"
+      return 0
+    fi
+
     if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
       exit 1
     else
@@ -910,7 +944,13 @@ create_target()
         fi
 	if [[ $(kubectl get target "$target_name" -n "$target_namespace" 2>/dev/null) ]];
         then
-          echo "Target with same name already exists"
+          if kubectl get target "$target_name"  -n  "$target_namespace" -o 'jsonpath={.status.status}' 2>/dev/null | grep -q Unavailable; then
+            echo "Target with same name already exists but is in Unavailable state"
+            return 1
+          else
+            echo "Target with same name already exists"
+	    return 0
+          fi
 	  if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
             exit 1
 	  else
@@ -978,7 +1018,7 @@ sample_test()
       if_resource_exists_still_proceed='y'
    fi
    if [[ -z "$backup_namespace" ]]; then
-      backup_namespace=trilio-test-backup
+      backup_namespace="trilio-test-backup"
    fi
    if [[ -z "$backup_name" ]]; then
       backup_name="trilio-test-backup"
@@ -1062,6 +1102,13 @@ EOM
 	  if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
             exit 1
           fi
+	  echo "Waiting for application to be in Ready state"
+	  cmd="kubectl get pods -l app=mysql-qa -n $backup_namespace 2>/dev/null | grep Running"
+	  wait_install 15 "$cmd"
+          if ! kubectl get pods -l app=mysql-qa -n $backup_namespace 2>/dev/null | grep -q Running; then
+            echo "Application taking more time than usual to be in Ready state, Exiting.."
+            exit 1
+          fi
         else
           helm install mysql-qa stable/mysql -n $backup_namespace 1>> >(logit) 2>> >(logit)
           echo "Installing Application"
@@ -1072,9 +1119,9 @@ EOM
             return 1
           fi
 	  echo "Requested application is installed successfully"
-          yq eval -i 'del(.spec.backupPlanComponents)' backupplan.yaml 1>> >(logit) 2>> >(logit)
-          yq eval -i '.spec.backupPlanComponents.custom[0].matchLabels.app="mysql-qa"' backupplan.yaml 1>> >(logit) 2>> >(logit)
         fi
+	yq eval -i 'del(.spec.backupPlanComponents)' backupplan.yaml 1>> >(logit) 2>> >(logit)
+	yq eval -i '.spec.backupPlanComponents.custom[0].matchLabels.app="mysql-qa"' backupplan.yaml 1>> >(logit) 2>> >(logit)
 	;;
       2)
 	if helm list -n $backup_namespace | grep -w -q my-wordpress 2>> >(logit);
@@ -1083,40 +1130,49 @@ EOM
 	  if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
             exit 1
           fi
+	  echo "Waiting for application to be in Ready state"
 	else
 	  #Add bitnami helm repo
 	  helm repo add bitnami https://charts.bitnami.com/bitnami 1>> >(logit) 2>> >(logit)
           helm install my-wordpress bitnami/wordpress -n $backup_namespace 1>> >(logit) 2>> >(logit)
 	  echo "Installing Application"
-	  runtime=20
-          spin='-\|/'
-          i=0
-          endtime=$(python3 -c "import time;timeout = int(time.time()) + 60*$runtime;print(\"{0}\".format(timeout))")
-	  while [[ $(python3 -c "import time;timeout = int(time.time());print(\"{0}\".format(timeout))") -le $endtime ]] && kubectl get pod -l  app.kubernetes.io/instance=my-wordpress -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False
-          do
-            i=$(( (i+1) %4 ))
-            printf "\r %s" "${spin:$i:1}"
-            sleep .1
-          done 
-	  if kubectl get pod -l  app.kubernetes.io/instance=my-wordpress -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False;then
-            echo "Wordpress installation failed"
-	    return 1
-	  fi
-	  echo "Requested application is installed successfully"
-	  yq eval -i 'del(.spec.backupPlanComponents)' backupplan.yaml 1>> >(logit) 2>> >(logit)
 	fi
+	runtime=20
+        spin='-\|/'
+        i=0
+        endtime=$(python3 -c "import time;timeout = int(time.time()) + 60*$runtime;print(\"{0}\".format(timeout))")
+	while [[ $(python3 -c "import time;timeout = int(time.time());print(\"{0}\".format(timeout))") -le $endtime ]] && kubectl get pod -l  app.kubernetes.io/instance=my-wordpress -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False
+        do
+          i=$(( (i+1) %4 ))
+          printf "\r %s" "${spin:$i:1}"
+          sleep .1
+        done 
+	if kubectl get pod -l  app.kubernetes.io/instance=my-wordpress -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False;then
+          echo "Wordpress Application taking more time than usual to be in Ready state, Exiting.."
+	  return 1
+	fi
+	echo "Requested application is Up and Running!"
+	yq eval -i 'del(.spec.backupPlanComponents)' backupplan.yaml 1>> >(logit) 2>> >(logit)
 	;;
 
       3)
-        echo "MySQL operator will require enough resources, else the deployment will fail"
-        helm repo add presslabs https://presslabs.github.io/charts 1>> >(logit) 2>> >(logit)
-        errormessage=$(helm install mysql-operator presslabs/mysql-operator -n $backup_namespace 2>> >(logit))
-        if echo "$errormessage"  | grep -Eq 'Error:|error:'; then
-          echo "Mysql operator Installation failed with error: $errormessage"
-          return 1
-        fi
-        echo "Installing MySQL Operator..."
-	echo "Installing Application"
+	if helm list -n $backup_namespace | grep -w -q mysql-operator 2>> >(logit);
+        then
+          echo "Application exists"
+          if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
+            exit 1
+          fi
+          echo "Waiting for application to be in Ready state"
+        else
+          echo "MySQL operator will require enough resources, else the deployment will fail"
+          helm repo add presslabs https://presslabs.github.io/charts 1>> >(logit) 2>> >(logit)
+          errormessage=$(helm install mysql-operator presslabs/mysql-operator -n $backup_namespace 2>> >(logit))
+          if echo "$errormessage"  | grep -Eq 'Error:|error:'; then
+            echo "Mysql operator Installation failed with error: $errormessage"
+            return 1
+          fi
+          echo "Installing MySQL Operator..."
+	fi
         runtime=15
         spin='-\|/'
         i=0
@@ -1128,18 +1184,23 @@ EOM
           sleep .1
         done
         if kubectl get pod -l app=mysql-operator -n $backup_namespace  -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False;then
-          echo "MySQL operator installation failed"
+          echo "MySQL operator taking more time than usual to be in Ready state, Exiting.."
           return 1
         fi
-        #Create a MySQL cluster
-        kubectl apply -f https://raw.githubusercontent.com/bitpoke/mysql-operator/master/examples/example-cluster-secret.yaml -n $backup_namespace 2>> >(logit)
-        kubectl apply -f https://raw.githubusercontent.com/bitpoke/mysql-operator/master/examples/example-cluster.yaml -n $backup_namespace 2>> >(logit)
+	if ! kubectl get pods -l mysql.presslabs.org/cluster=my-cluster -n $backup_namespace  --ignore-not-found 1>> >(logit);then
+	  echo "Mysql cluster already exists.."
+	  echo "Waiting for application to be in Ready state"
+	else
+          #Create a MySQL cluster
+          kubectl apply -f https://raw.githubusercontent.com/bitpoke/mysql-operator/master/examples/example-cluster-secret.yaml -n $backup_namespace 2>> >(logit)
+          kubectl apply -f https://raw.githubusercontent.com/bitpoke/mysql-operator/master/examples/example-cluster.yaml -n $backup_namespace 2>> >(logit)
+	  echo "Installing MySQL cluster..."
+          sleep 10
+	fi
 	runtime=15
         spin='-\|/'
         i=0
         endtime=$(python3 -c "import time;timeout = int(time.time()) + 60*$runtime;print(\"{0}\".format(timeout))")
-        echo "Installing MySQL cluster..."
-        sleep 10
         while [[ $(python3 -c "import time;timeout = int(time.time());print(\"{0}\".format(timeout))") -le $endtime ]] && kubectl get pods -l mysql.presslabs.org/cluster=my-cluster -n $backup_namespace  -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False
         do
           i=$(( (i+1) %4 ))
@@ -1154,9 +1215,10 @@ EOM
           sleep .1
         done
         if kubectl get pods -l mysql.presslabs.org/cluster=my-cluster -n $backup_namespace  -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False;then
-          echo "MySQL cluster installation failed"
+          echo "MySQL cluster taking more time than usual to be in Ready state, Exiting.."
           return 1
         fi
+	echo "Requested application is Up and Running!"
 	#Creating backupplan
 	{
  	  yq eval -i 'del(.spec.backupPlanComponents)' backupplan.yaml
@@ -1176,6 +1238,7 @@ EOM
 	  if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
             exit 1
           fi
+	  echo "Waiting for application to be in Ready state"
         else
           {
 	    helm repo add bitnami https://charts.bitnami.com/bitnami
@@ -1183,24 +1246,24 @@ EOM
             helm install mongotest bitnami/mongodb -n $backup_namespace
 	  } 2>> >(logit)
 	  echo "Installing App..."
-	  runtime=15
-          spin='-\|/'
-          i=0
-          endtime=$(python3 -c "import time;timeout = int(time.time()) + 60*$runtime;print(\"{0}\".format(timeout))")
-	  while [[ $(python3 -c "import time;timeout = int(time.time());print(\"{0}\".format(timeout))") -le $endtime ]] && kubectl get pod -l app.kubernetes.io/name=mongodb -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q -w False
-          do
-            i=$(( (i+1) %4 ))
-            printf "\r %s" "${spin:$i:1}"
-            sleep .1
-          done
-	  if kubectl get pod -l app.kubernetes.io/name=mongodb -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False;then
-            echo "Mongodb installation failed"
-            return 1
-          fi
-	  echo "Requested application is installed successfully"
-          yq eval -i 'del(.spec.backupPlanComponents)' backupplan.yaml 1>> >(logit) 2>> >(logit)
-	  yq eval -i '.spec.backupPlanComponents.helmReleases[0]="mongotest"' backupplan.yaml 1>> >(logit) 2>> >(logit)
 	fi
+	runtime=15
+        spin='-\|/'
+        i=0
+        endtime=$(python3 -c "import time;timeout = int(time.time()) + 60*$runtime;print(\"{0}\".format(timeout))")
+	while [[ $(python3 -c "import time;timeout = int(time.time());print(\"{0}\".format(timeout))") -le $endtime ]] && kubectl get pod -l app.kubernetes.io/name=mongodb -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q -w False
+        do
+          i=$(( (i+1) %4 ))
+          printf "\r %s" "${spin:$i:1}"
+          sleep .1
+        done
+	if kubectl get pod -l app.kubernetes.io/name=mongodb -n $backup_namespace -o  jsonpath="{.items[*].status.conditions[*].status}" | grep -q False;then
+          echo "Mongodb Application taking more time than usual to be in Ready state, Exiting.."
+          return 1
+        fi
+	echo "Requested application is Up and Running!"
+        yq eval -i 'del(.spec.backupPlanComponents)' backupplan.yaml 1>> >(logit) 2>> >(logit)
+	yq eval -i '.spec.backupPlanComponents.helmReleases[0]="mongotest"' backupplan.yaml 1>> >(logit) 2>> >(logit)
 	;;
       *)
     	echo "Wrong choice"
@@ -1213,6 +1276,7 @@ EOM
         if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
           exit 1
         fi
+	echo "Waiting for Backupplan to be in Available state"
    else
      #Applying backupplan manifest
      {
@@ -1245,16 +1309,16 @@ EOF
           echo "Backupplan creation failed"
           return 1
      fi
-     cmd="kubectl get backupplan $bk_plan_name  -n  $backup_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -e Available -e Unavailable"
-     wait_install 10 "$cmd"
-     if ! kubectl get backupplan $bk_plan_name  -n  $backup_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -q Available; then
-       echo "Backupplan creation failed"
-       return 1
-     else
-       echo "Backupplan is in Available state"
-     fi
-
    fi
+   cmd="kubectl get backupplan $bk_plan_name  -n  $backup_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -e Available -e Unavailable"
+   wait_install 10 "$cmd"
+   if ! kubectl get backupplan $bk_plan_name  -n  $backup_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -q Available; then
+     echo "Backupplan is in Unavailable state"
+     return 1
+   else
+     echo "Backupplan is in Available state"
+   fi
+
    rm -f backupplan.yaml
    if [[ $(kubectl get backup $backup_name  -n  $backup_namespace 2>> >(logit)) ]];
       then
@@ -1262,6 +1326,7 @@ EOF
         if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
           exit 1
         fi
+        echo "Waiting for Backup to be in Available state"
    else
      echo "Creating Backup..."
      #Applying backup manifest
@@ -1282,14 +1347,14 @@ EOF
        echo "Error while creating backup"
        return 1
      fi
-     cmd="kubectl get backup $backup_name -n  $backup_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -e Available -e Failed"
-     wait_install 60 "$cmd"
-     if ! kubectl get backup $backup_name -n $backup_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -wq Available; then
-       echo "Backup Failed"
-       return 1
-     else
-       echo "Backup is Available Now"
-     fi
+   fi
+   cmd="kubectl get backup $backup_name -n  $backup_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -e Available -e Failed"
+   wait_install 60 "$cmd"
+   if ! kubectl get backup $backup_name -n $backup_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -wq Available; then
+     echo "Backup Failed"
+     return 1
+   else
+     echo "Backup is Available Now"
    fi
    if  [[ -z ${input_config} ]];then
      read -r -p "whether restore test should also be done? y/n: " restore
@@ -1324,6 +1389,7 @@ EOF
         if [[ "$if_resource_exists_still_proceed" != "Y" ]] && [[ "$if_resource_exists_still_proceed" != "y" ]];then
           exit 1
         fi
+	echo "Waiting for Restore to be in Available state"
      else
      echo "Creating restore..."
      #Applying restore manifest
@@ -1350,14 +1416,14 @@ EOF
          echo "Error while restoring"
 	 return 1
        fi
-       cmd="kubectl get restore $restore_name -n $restore_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -e Completed -e Failed"
-       wait_install 60 "$cmd"
-       if ! kubectl get restore $restore_name -n $restore_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -wq 'Completed'; then
-         echo "Restore Failed"
-         return 1
-       else
-         echo "Restore is Completed"
-       fi
+     fi
+     cmd="kubectl get restore $restore_name -n $restore_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -e Completed -e Failed"
+     wait_install 60 "$cmd"
+     if ! kubectl get restore $restore_name -n $restore_namespace -o 'jsonpath={.status.status}' 2>/dev/null | grep -wq 'Completed'; then
+       echo "Restore Failed"
+       return 1
+     else
+       echo "Restore is Completed"
      fi
    fi
 }
